// vue-hw/src/views/Following.vue
<template>
 <div>
     <h1> Following users</h1>
      <div class="cardsHolder" v-for="user in following" :key="user.login">
        <div class="card followingCard">
          <img width="100px" height="100px" :src="user.avatar_url" />
          <h4>{{user.login}}</h4>
        </div>
      </div>
    </div>
</template>

<script>

import { getUserFollowings } from "../http";

export default {
  name: "following",
  data: function() {
    return {
      following: []
    };
  },
  created: function() {
    this.following = [];
    getUserFollowings(this.$route.params.login)
      .then(response => {
        this.following = response.data;
      })
      .catch(() => {
        this.following = [];
      });
  }
};
</script>
<style>
.followingCard {
  display: inline-flex;
  width: 100%;
}
.followingCard h4 {
  padding: 1em;
}
</style>

// angular-hw/src/app/following.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
import { GithubService } from "./app.service";

@Component({
  selector: "app-following",
  template: `
    <div>
     <h1> Following users</h1>
      <div class="cardsHolder" *ngFor="let user of followingUsers">
        <div class="card followingCard">
          <img width="100px" height="100px" src="{{user.avatar_url}}" />
          <h4>{{user.login}}</h4>
        </div>
      </div>
    </div>
  `,
  styles: [
    `.followingCard{
    display: inline-flex;
    width: 100%;
  }
  .followingCard h4{
    padding:1em;
  }`
  ]
})
export class FollowingComponent implements OnInit {
  followingUsers: Object;
  constructor(
    private route: ActivatedRoute,
    private githubService: GithubService
  ) {}

  ngOnInit() {
    this.getFollowingUsers();
  }

  getFollowingUsers(): void {
    this.githubService
      .getUserFollowings(this.route.snapshot.paramMap.get("login"))
      .subscribe(followingUsers => (this.followingUsers = followingUsers));
  }
}
