// vue-hw/src/views/Following.vue
<template>
 <div>
     <h1> Following users</h1>
      <div class="cardsHolder" v-for="user in following" :key="user.login">
        <div class="card followingCard">
          <img width="100px" height="100px" :src="user.avatar_url" />
          <h4>{{user.login}}</h4>
        </div>
      </div>
    </div>
</template>

<script>

import { getUserFollowings } from "../http";

export default {
  name: "following",
  data: function() {
    return {
      following: []
    };
  },
  created: function() {
    this.following = [];
    getUserFollowings(this.$route.params.login)
      .then(response => {
        this.following = response.data;
      })
      .catch(() => {
        this.following = [];
      });
  }
};
</script>
<style>
.followingCard {
  display: inline-flex;
  width: 100%;
}
.followingCard h4 {
  padding: 1em;
}
</style>

// react-hw/src/Following.js
import React, { Component } from 'react';
import { getUserFollowings } from './http';
export class Following extends Component {
  state = { repositories: [] };

  fetchFollowing(login) {
    getUserFollowings(login).then(
      response => this.setState({ repositories: response.data }),
      () => this.setState({ repositories: [] }),
    );
  }

  componentDidUpdate(prevProps) {
    if (this.props.match.params.login !== prevProps.match.params.login) {
      this.fetchFollowing(this.props.match.params.login);
    }
  }
  componentDidMount() {
    this.fetchFollowing(this.props.match.params.login);
  }

  render() {
    return (
      <div>
        <h1> Following users</h1>
        <div className="cardsHolder">
          {this.state.repositories.map(user => (
            <div className="card followingCard" key={user.login}>
              <img width="100px" height="100px" src={user.avatar_url} />
              <h4>{user.login}</h4>
            </div>
          ))}
        </div>
      </div>
    );
  }
}
