// vue-hw/src/views/Repositories.vue
<template>
 <div>
     <h1> Repositories </h1>
      <div class="cardsHolder" v-for="repository in repositores" :key="repository.id">
        <div class="card">
       <div class="firstLine"> <h4>{{repository.name}}</h4> <i>{{repository.language}}</i></div>
        <p>{{repository.description}}</p></div>
      
      </div>
    </div>
</template>

<script>
import { getUsersRepos } from "../http";

export default {
  name: "repositories",
  data: function() {
    return {
      repositores: []
    };
  },
  created: function() {
    this.repositores = [];
    getUsersRepos(this.$route.params.login)
      .then(response => {
        this.repositores = response.data;
      })
      .catch(() => {
        this.repositores = [];
      });
  }
};
</script>
<style>
.firstLine {
  display: inline-flex;
}
.firstLine i {
  padding: 1.3em;
}
</style>

// react-hw/src/Repositories.js
import React, { Component } from 'react';
import { getUsersRepos } from './http';
export class Repositories extends Component {
  state = { repositories: [] };

  fetchRepositories(login) {
    getUsersRepos(login).then(
      response => this.setState({ repositories: response.data }),
      () => this.setState({ repositories: [] }),
    );
  }

  componentDidUpdate(prevProps) {
    if (this.props.match.params.login !== prevProps.match.params.login) {
      this.fetchRepositories(this.props.match.params.login);
    }
  }
  componentDidMount() {
    this.fetchRepositories(this.props.match.params.login);
  }

  render() {
    return (
      <div>
        <h1> Repositories </h1>
        <div className="cardsHolder">
          {this.state.repositories.map(repository => (
            <div className="card" key={repository.id}>
              <div className="firstLine">
                <h4>{repository.name}</h4> <i>{repository.language}</i>
              </div>
              <p>{repository.description}</p>
            </div>
          ))}
        </div>
      </div>
    );
  }
}
